---
name: wud
working_dir: apps/system/wud
---
name: code
working_dir: apps/system/code-server
---
name: gatus
working_dir: apps/observability/gatus
---
name: gotify
working_dir: apps/networking/gotify
