# system
---
name: homepage
working_dir: apps/system/homepage
---
name: wud
working_dir: apps/system/wud
---
name: prunemate
working_dir: apps/system/prunemate
---
name: code
working_dir: apps/system/code-server
---
name: wol
working_dir: apps/system/wol
---
name: amialive
working_dir: apps/system/amialive

# observability
---
name: gatus
working_dir: apps/observability/gatus

# networking
---
name: gotify
working_dir: apps/networking/gotify
---
name: cloudflared
working_dir: apps/networking/cloudflared
